version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis_data:/data

